spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: 'cmUGfdJ8sKYorlt_EsoN'
            client-secret: '_BEVPrAAbp'
          kakao:
            clientId: '7b775bf668fefd7bde46f09667d37e4e'
          google:
            clientId: '779926395218-seeha819p5g97t3t1vifmk5ph5d896ij.apps.googleusercontent.com'
            client-secret: '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;
INSTA_CLIENT ID=773014957633773'
          facebook:
            clientId: '601003835301642'
            client-secret: '5fb0fdd53b9177fd6bf68822672abac3'
          instagram:
            clientId: '773014957633773'
            client-secret: 'ea5eec0244e36b28c7401597bd3350e9'