spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/gram__prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldjlocal
    password: 1234
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: 'http://101.101.217.17/{action}/oauth2/code/{registrationId}'
          kakao:
            redirect-uri: 'http://101.101.217.17/{action}/oauth2/code/{registrationId}'
          google:
            redirect-uri: 'http://101.101.217.17/{action}/oauth2/code/{registrationId}'
          facebook:
            redirect-uri: 'http://101.101.217.17/{action}/oauth2/code/{registrationId}'
          instagram:
            redirect-uri: 'http://101.101.217.17/{action}/oauth2/code/{registrationId}'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
logging:
  level:
    root: INFO
    com.ll.gramgram: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO